module.exports = {
    "arn": "ARN stands for application resource name. It\'s an id for your Lambda function and connects the function to the skill definition on the developer portal. You could say It\'s the key that connects front end and back end together.",
    "a r n": "ARN stands for application resource name. It\'s an id for your Lambda function and connects the function to the skill definition on the developer portal. You could say It\'s the key that connects front end and back end together.",
    "a. r. n.": "ARN stands for application resource name. It\'s an id for your Lambda function and connects the function to the skill definition on the developer portal. You could say It\'s the key that connects front end and back end together.",
    "begin my skill": "There are several keywords you can use to launch your skill. Just say launch, begin, start, or open and the invocation name for your skill.",
    "build a skill": "To get started building skills, you need three things: an aws account, a developer account, and the sample templates on GitHub. Just go to bit dot ly slash alexa quick start, and see the getting started section. Again, that URL is bit.ly/alexa quick start. Have fun!",
    "build skills": "To get started building skills, you need three things: an aws account, a developer account, and the sample templates on GitHub. Just go to bit dot ly slash alexa quick start, and see the getting started section. Again, that URL is bit.ly/alexa quick start . Have fun!",
    "card": "Cards appear in the Alexa app online and on your smart phone. In addition to the verbal response, you also get a graphical response from each spoken request. Pretty cool! Wouldn\'t you agree?",
    "cards": "Cards appear in the Alexa app online and on your smart phone. In addition to the verbal response, you also get a graphical response from each spoken request. Pretty cool! Wouldn\'t you agree?",
    "change alexas pronunciation": "You can change my pronunciation by using SSML tags. To learn more take a look at this page: bit.ly/ssml, dash, how, dash, to. ",
    "change your pronunciation": "You can change my pronunciation by using SSML tags. To learn more take a look at this page: bit.ly/ssml, dash, how, dash, to. ",
    "change the card title": "Card titles can be manipulated with javascript and It\'s pretty easy to do. Just search on javascript strings and you'll find plenty of code snippets.",
    "change the card titles": "Card titles can be manipulated with javascript and It\'s pretty easy to do. Just search on javascript strings and you'll find plenty of code snippets.",
    "change card titles": "Card titles can be manipulated with javascript and It\'s pretty easy to do. Just search on javascript strings and you'll find plenty of code snippets.",
    "change your pronunciation": "You can change my pronunciation by using SSML tags. To learn more take a look at this page: bit.ly/ssml, dash, how, dash, to. ",
    "check in": "To check in, please go to bit.ly/ alexa checkin.",
    "check in to my event": "To check in, please go to bit.ly/ alexa checkin.",
    "claim my device": "If you've published three skills, go to bit.ly/ alexa boot camp... and fill out the form.",
    "constants": "There are several built-in intents or constants. Some of these include, dates, numbers, yes, no, and help intents. See the sample templates for examples.",
    "custom slot type": "A custom slot type defines a variable type. Just like other strongly typed languages, you need to declare the variable or slot type.",
    "custom slot types": "A custom slot type defines a variable type. Just like other strongly typed languages, you need to declare the variable or slot type.",
    "custom slot": "A custom slot type defines a variable type. Just like other strongly typed languages, you need to declare the variable or slot type.",
    "custom slots": "A custom slot type defines a variable type. Just like other strongly typed languages, you need to declare the variable or slot type.",
    "customize the card title": "Card titles can be manipulated with javascript and It\'s pretty easy to do. Just search on javascript strings and you'll find plenty of code snippets.",
    "download the samples": "You can get the samples from git hub.com/alexa. I recommend you make the Fact Skill first, then try How To, or Decision Tree.",
    "download the templates": "You can get the samples from git hub.com/alexa. I recommend you make the Fact Skill first, then try How To, or Decision Tree.",
    "find the github repo": "You can find the repo on git hub.com/alexa.  I recommend you make the Fact Skill first, then try How To, or Decision Tree.",
    "find the github samples": "You can find the samples on git hub.com/alexa . I recommend you make the Fact Skill first, then try How To, or Decision Tree.",
    "find my app id": "To find your app ID, go to your skill on the developer portal. On the Skill Information tab, the app ID is located in the upper right corner.",
    "find my application id": "To find your app ID, go to your skill on the developer portal. On the Skill Information tab, the app ID is located in the upper right corner.",
    "find my application i d": "To find your app ID, go to your skill on the developer portal. On the Skill Information tab, the app ID is located in the upper right corner.",
    "find the arn": "You can find the a r n on the configuration tab or your Lambda function. By the way,  a r n stands for Amazon Resource Name, and ties your function to your skill definition on the developer portal.",
    "find the a r n": "You can find the a r n on the configuration tab or your Lambda function. By the way,  a r n stands for Amazon Resource Name, and ties your function to your skill definition on the developer portal.",
    "find the a. r. n.": "You can find the a r n on the configuration tab or your Lambda function. By the way,  a r n stands for Amazon Resource Name, and ties your function to your skill definition on the developer portal.",
    "find the repo": "You can find the repo on git hub.com/alexa . I recommend you make the Fact Skill first, then try How To, or Decision Tree.",
    "find the samples": "You can find the repo on git hub.com/alexa . I recommend you make the Fact Skill first, then try How To, or Decision Tree.",
    "find the sample templates": "You can find the repo on git hub.com/alexa . I recommend you make the Fact Skill first, then try How To, or Decision Tree.",
    "find the templates": "You can find the repo on git hub.com/alexa . I recommend you make the Fact Skill first, then try How To, or Decision Tree.",
    "fix the event source type": "Ah, I've seen this before. Just go back to your Lambda function and view the triggers tab. There, you need to add a new trigger for your Lambda function. To do this,  click the dotted drop down menu and select Alexa Skills Kit. Hit the submit button, then test your skill again.",
    "get a developer account": "Getting a developer account is easy, just go to developer.amazon.com. After signing in, go to the Alexa tab, then click on the left badge, alexa skills kit.",
    "get a device": "To get an Amazon device, attend a Hackathon event, and publish three skills within 30 days. Certain restrictions apply, see bit.ly/alexa boot camp for details.",
    "get a skill approved": "On average it takes 2-3 business days for skills to be tested. You\'ll get an email either way from the testing team. If your skill passes it will automatically be published. If your skill fails, you\'ll get detailed suggestions about what needs fixing.",
    "get a tap": "For a limited time, you can attend a hackathon event and qualify for a device. Publish three skills within 30 days of the event, and let us know about it. Certain restrictions apply, see bit.ly/ alexa boot camp for details.",
    "get an amazon device": "For a limited time, you can attend a hackathon event and qualify for a device. Publish three skills within 30 days of the event, and let us know about it. Certain restrictions apply, see bit.ly/ alexa boot camp for details.",
    "get an aws account": "To get an account, go to aws.amazon.com and sign up. Please note, you need a credit card, but the service is free for the first 1 million transactions per month. That\'s a threshold mainly for commercial developers, so no worries there.",
    "get an a. w. s. account": "To get an account, go to aws.amazon.com and sign up. Please note, you need a credit card, but the service is free for the first 1 million transactions per month. That\'s a threshold mainly for commercial developers, so no worries there.",
    "get an echo": "For a limited time, you can attend a hackathon event and qualify for a device. Publish three skills within 30 days of the event, and let us know about it. Certain restrictions apply, see bit.ly/ alexa boot camp for details.",
    "get assistance": "For further assistance, please contact any of our evangelists listed on the bit.ly/alexa quick start page.",
    "get further assistance": "For further assistance, please contact any of our evangelists listed on the bit.ly/alexa quick start page.",
    "get help": "For further assistance, please contact any of our evangelists listed on the bit.ly/alexa quick start page.",
    "get some help": "For further assistance, please contact any of our evangelists listed on the bit.ly/alexa quick start page.",   
    "get my device": "If you've published three skills, go to bit.ly/ alexa boot camp and fill out the form.",
    "get the a. r. n.": "After you create a Lambda function on the AWS portal, you'll see the ARN in the upper right corner of your screen.",
    "get skills approved": "On average it takes 2-3 business days for skills to be tested. You\'ll get an email either way from the testing team. If your skill passes it will automatically be published. If your skill fails, you\'ll get detailed suggestions about what needs fixing.",
    "get my skills approved": "On average it takes 2-3 business days for skills to be tested. You\'ll get an email either way from the testing team. If your skill passes it will automatically be published. If your skill fails, you\'ll get detailed suggestions about what needs fixing.",
    "get skills published": "On average it takes 2-3 business days for skills to be tested. You\'ll get an email either way from the testing team. If your skill passes it will automatically be published. If your skill fails, you\'ll get detailed suggestions about what needs fixing.",
    "get my skills published": "On average it takes 2-3 business days for skills to be tested. You\'ll get an email either way from the testing team. If your skill passes it will automatically be published. If your skill fails, you\'ll get detailed suggestions about what needs fixing.",
    "get skills tested": "On average it takes 2-3 business days for skills to be tested. You\'ll get an email either way from the testing team. If your skill passes it will automatically be published. If your skill fails, you\'ll get detailed suggestions about what needs fixing.",
    "get my skills tested": "On average it takes 2-3 business days for skills to be tested. You\'ll get an email either way from the testing team. If your skill passes it will automatically be published. If your skill fails, you\'ll get detailed suggestions about what needs fixing.",
    "get my skills certified": "On average it takes 2-3 business days for skills to be tested. You\'ll get an email either way from the testing team. If your skill passes it will automatically be published. If your skill fails, you\'ll get detailed suggestions about what needs fixing.",
    "get skills certified": "On average it takes 2-3 business days for skills to be tested. You\'ll get an email either way from the testing team. If your skill passes it will automatically be published. If your skill fails, you\'ll get detailed suggestions about what needs fixing.",
    "get some assistance": "For further assistance, please contact any of our evangelists listed on the bit.ly/alexa quick start page.",
    "get some help": "For further assistance, please contact any of our evangelists listed on the bit.ly/alexa quick start page.",
    "get started": "To get started making skills, you need three things: an aws account, a developer account, and the sample templates on GitHub. Just go to bit.ly/ alexa quick start (all one word), and see the getting started section. Again, that URL is bit.ly/ alexa quick start (all one word). Have fun! ",
    "get the samples": "You can find the repo on git hub.com/alexa . I recommend you make the Fact Skill first, then try How To, or Decision Tree.",
    "get the sample templates": "You can find the repo on git hub.com/alexa . I recommend you make the Fact Skill first, then try How To, or Decision Tree.",
    "get the templates":  "You can find the repo on git hub.com/alexa . I recommend you make the Fact Skill first, then try How To, or Decision Tree.",
    "intent": "Intents are capabilities, or things your skill can do. customers speak utterances, which map to intents, which then trigger functions in your code. Each intent triggers a specific function.",
    "intents": "Intents are capabilities, or things your skill can do. customers speak utterances, which map to intents, which then trigger functions in your code. Each intent triggers a specific function.",
    "intent schema": "The intent schema is a JSON structure, which declares the capabilities your skills has.  In other words, it defines the intents and slot types your skill uses.",
    "invocation name": "The invocation name is what you say to launch your skill. Take a look at the skill information tab on the developer portal again. At the bottom you\'ll see the invocation name.",
    "lambda": "Lambda is an AWS compute service that runs your code in response to events, and automatically manages all resources for you. This lets you run code in the cloud without managing servers. Lambda supports coding in Node dot js, Java, and Python.",
    "launch my skill": "There are several keywords you can use to launch your skill. Just say launch, begin, start, or open and the invocation name for your skill.",
    "make a skill": "To get started making skills, you need three things: an aws account, a developer account, and the sample templates on GitHub. Just go to bit dot ly slash alexa quick start, and see the getting started section. Again, that URL is bit.ly/alexa quick start. Have fun! ",
    "make an http request": "To make an http request, take a look at the history template. You'll see an http get call near the top of the index.js file. You can find this sample in an older collection on git hub.com/ a m z n, just look for the alexa skills kit j s.",
    "make icons": "To make icons, I have a great suggestion for you. Check out this tool tool for PC and Mac, just go to iconion.com. Iconion is spelled i c o n i o n.",
    "make skills": "To get started making skills, you need three things: an aws account, a developer account, and the sample templates on GitHub. Just go to bit dot ly slash alexa quick start, and see the getting started section. Again, that URL is bit.ly/alexa quick start . Have fun!",
    "open my skill" : "There are several keywords you can use to launch your skill. Just say launch, begin, start, or open and the invocation name for your skill.",
    "publish flash cards": "Only if you make it your own. That means you need to change the title to something other than Flash Cards or Chemistry Flash Cards. Of course, you also need to change all of the questions, answers, slot values, and content strings in your code.",
    "publish a skill": "To publish a skill, go to the developer portal, and select the publishing tab. Be sure and enter the name of the event, and sample template you used, in the notes section.",
    "publish my skills": "To publish a skill, go to the developer portal, and select the publishing tab. Be sure and enter the name of the event, and sample template you used, in the notes section.",
    "register for my event": "To register or sign in to your event, please go to bit.ly/ alexa checkin.",
    "republish your templates": "Sorry, no. You need to make the skills your own before submitting for certification. This means changing all of the content. More specifically, you need to change the name of the skill and invocation name,  slot values, questions, and answers. Remember, there are custom strings in the intent handler functions too.",
    "sample": "The easiest one is the Fact Skill. Then try the Trivia Quiz, or the How-To skill. As a matter of fact, Liz Myers used the How To template to make this skill!",
    "setup echo": "To setup your device, go to alexa.amazon.com. From the left hand menu, go to settings, and then select, setup a new device.",
    "setup the echo": "To setup your device, go to alexa.amazon.com. From the left hand menu, go to settings, and then select, setup a new device.",
    "setup my device": "To setup your device, go to alexa.amazon.com. From the left hand menu, go to settings, and then select, setup a new device.",
    "setup tap": "To setup your device, go to alexa.amazon.com. From the left hand menu, go to settings, and then select, setup a new device.",
    "setup the tap": "To setup your device, go to alexa.amazon.com. From the left hand menu, go to settings, and then select, setup a new device.",
    "setup the device": "To setup your device, go to alexa.amazon.com. From the left hand menu, go to settings, and then select, setup a new device.",
    "setup your device": "To setup your device, go to alexa.amazon.com. From the left hand menu, go to settings, and then select, setup a new device.",
    "show you my three skills": "Congratulations on getting all three sklls published. Just fill out the form on bit.ly/alexa boot camp and we'll send you an Echo or Tap device.",
    "show you my three skills in order to get a device": "Congratulations on getting all three sklls published. Just fill out the form on bit.ly/alexa boot camp and we'll send you an Echo or Tap device.",
    "show you the three skills I published": "Congratulations on getting all three sklls published. Just fill out the form on bit.ly/alexa boot camp and we'll send you an Echo or Tap device.",
    "skill": "The easiest one is the Fact Skill. Then try the Trivia Quiz, or the How-To skill. As a matter of fact, Liz Myers used the How To template to make this skill!",
    "skills": "Skills are new capabilities you can build for Alexa, and by doing so, both of you become smarter. ",
    "slot": "Slots are variables, and when your skill is active, I listen for them intently. Ha ha, intently and intents - got that? Anyway, I watch for intents and slot values, so I can trigger the right functions and pass the right variables.",
    "slots": "Slots are variables, and when your skill is active, I listen for them intently. Ha ha, intently and intents - got that? Anyway, I watch for intents and slot values, so I can trigger the right functions and pass the right variables.",
    "start my skill": "There are several keywords you can use to launch your skill. Just say launch, begin, start, or open and the invocation name for your skill.",
    "ssml": "SSML stands for speech synthesis markup language.  With SSML you can better control pronunciation, timing, and inflection. With SSML you can also play audio clips. To learn more, go to bit.ly/ssml, dash, how, dash, to.",
    "submit a skill for certification": "To publish a skill, go to the developer portal, and select the publishing tab. Be sure and enter the name of the event, and sample template you used, in the notes section.",
    "submit a skill": "To publish a skill, go to the developer portal, and select the publishing tab. Be sure and enter the name of the event, and sample template you used, in the notes section.",
    "submit my skill for certification": "To publish a skill, go to the developer portal, and select the publishing tab. Be sure and enter the name of the event, and sample template you used, in the notes section.",
    "submit my skills": "To publish a skill, go to the developer portal, and select the publishing tab. Be sure and enter the name of the event, and sample template you used, in the notes section.",
    "submit my skills for certification": "To publish a skill, go to the developer portal, and select the publishing tab. Be sure and enter the name of the event, and sample template you used, in the notes section.",
    "template": "The easiest one is the Fact Skill. Then try the Trivia Quiz, or the How-To skill. As a matter of fact, Liz Myers used the How To template to make this skill!",
    "test a skill": "You can test your skills online. Just go to echosim.io and log in with your developer email and password",
    "test my skill": "You can test your skills online. Just go to echosim.io and log in with your developer email and password.",
    "test my skills": "You can test your skills online. Just go to echosim.io and log in with your developer email and password.",
    "use audio": "There\'s a great video tutorial for working with audio clips on the web. Go to bit.ly/ssml, and, audio for details.",
    "use audio clips": "There\'s a great video tutorial for working with audio clips on the web. Go to bit.ly/ssml, and, audio, for details.",
    "utterance": "Utterances are things you humans say to me. Because I'm not always listening, I can\'t infer meaning from context, so I need to capture specific words or small groups of words, and map them to a given intent. The related intent triggers a function in your code.",
    "utterances": "Utterances are things you humans say to me. Because I'm not always listening, I can\'t infer meaning from context, so I need to capture specific words or small groups of words, and map them to a given intent. The related intent triggers a function in your code.",
    "work with audio": "There\'s a great video tutorial for working with audio clips on the web. Go to bit.ly/ssml, and, audio.",
    "work with audio clips": "There\'s a great video tutorial for working with audio clips on the web. Go to bit.ly/ssml, and, audio."
};
